#!/usr/bin/env python3
import sys
import os
import argparse
import yaml
import keyring
import getpass
import gkeepapi
import urwid
import logging
from keep_cli import application, constants
from uuid import getnode as get_mac

logger = logging.getLogger('keep-cli')
logger.setLevel(logging.INFO)
ch = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter('[%(levelname)s] %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

parser = argparse.ArgumentParser('Keep-CLI')
parser.add_argument('--config-dir', type=str, default='~/.keep', help='Configuration directory')
parser.add_argument('--offline', action='store_true', help='Offline mode')

args = parser.parse_args()

config_dir = os.path.expanduser(args.config_dir)
if not os.path.isdir(config_dir):
    os.makedirs(config_dir)

config_file = os.path.join(config_dir, 'config.yml')
config = {}
if os.path.isfile(config_file):
    with open(config_file, 'r') as fh:
        config = yaml.load(fh, Loader=yaml.Loader)
else:
    config = {
        'username': input('Username: '),
        'views': {
            'default': {
                'name': 'Default',
                'type': 'grid',
            },
        },
    }
    with open(config_file, 'w') as fh:
        yaml.dump(config, fh, default_flow_style=False)

keep = gkeepapi.Keep()

logged_in = args.offline

token = keyring.get_password('google-keep-token', config['username'])
if not logged_in and token:
    logger.info('Authenticating with token')
    try:
        keep.resume(config['username'], token, sync=False)
        logged_in = True
        logger.info('Success')
    except gkeepapi.exception.LoginException:
        logger.info('Invalid token')

if not logged_in:
    password = getpass.getpass()
    try:
        keep.login(config['username'], password, sync=False)
        logged_in = True
        del password
        token = keep.getMasterToken()
        keyring.set_password('google-keep-token', config['username'], token)
        logger.info('Success')
    except gkeepapi.exception.LoginException:
        logger.info('Login failed')

if not logged_in:
    print('[+] Failed to authenticate')
    sys.exit(1)

app = application.Application(keep, config, config_dir, args.offline)
loop = urwid.MainLoop(app, constants.Palette)
loop.screen.set_terminal_properties(colors=256)
try:
    loop.run()
except KeyboardInterrupt:
    pass
