#!/usr/bin/env python3
import argparse, application, yaml, keyring, gkeepapi, urwid, constants

parser = argparse.ArgumentParser('Keep-CLI')
parser.add_argument('--config', type=str, default='config.yml', help='Configuration file')

args = parser.parse_args()

fh = open(args.config, 'r')
config = yaml.load(fh, Loader=yaml.Loader)
fh.close()

password = keyring.get_password('google-keep', config['username'])

keep = gkeepapi.Keep()
keep.login(config['username'], password)
password = None

app = application.Application(keep)
loop = urwid.MainLoop(application.Application(config, keep), constants.Palette)
loop.screen.set_terminal_properties(colors=256)
loop.run()
